services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB:   ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    depends_on:
      - db
    # Берём переменные из .env (docker-compose читает его автоматически)
    environment:
      TELEGRAM_TOKEN_WATER: ${TELEGRAM_TOKEN_WATER}
      DB_NAME:        ${DB_NAME}
      DB_USER:        ${DB_USER}
      DB_PASS:        ${DB_PASS}
      DB_HOST:        db
      DB_PORT:        ${DB_PORT}
    # Для разработки пробросим код внутрь (чтобы не пересобирать образ при каждом изменении)
    volumes:
      - .:/app
    command: ["python", "-m", "src.main"]

volumes:
  postgres_data:
